FROM python:3.9

RUN apt-get -qq clean && apt-get -qq update --fix-missing
RUN apt-get -qq install -y ffmpeg

RUN ffmpeg -version

WORKDIR /tmp

RUN mkdir download_videos
RUN mkdir media

WORKDIR /app

COPY moviepy-test.py moviepy-test.py

COPY requirements.txt .

RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN echo "$PWD"

CMD [ "python", "moviepy-test.py" ]
